In [1]:
import numpy as np
from dtw import dtw_basic, dtw_fast

s1 = np.array([0, 1, 1, 3, 5])
s2 = np.array([0, 1, 5, 3, 4, 0, 1, 5, 3])

# Základní varianta DTW

In [2]:
[cost, D] = dtw_basic(s1, s2)
print(cost)
print(D)

10
[[ 0  1  6  9 13 13 14 19 22]
 [ 1  0  4  6  9 10 10 14 16]
 [ 2  0  4  6  9 10 10 14 16]
 [ 5  2  2  2  3  6  8 10 10]
 [10  6  2  4  3  8 10  8 10]]


#  Varianta DTW s omezením výpočtu pro zvolené okno

In [3]:
[cost, D] = dtw_fast(s1, s2, window=5)
print(cost)
print(D)

10
[[         0          1          2 2147483647 2147483647]
 [         1          0          0 2147483647 2147483647]
 [         6          4          4          2 2147483647]
 [         9          6          6          2 2147483647]
 [        13          9          9          3          3]
 [        13         10         10          6          8]
 [2147483647         10         10          8         10]
 [2147483647         14         14         10          8]
 [2147483647 2147483647         16         10         10]]


In [4]:
[cost, D] = dtw_fast(s1, s2, window=3)
print(cost)
print(D)

14
[[         0          1 2147483647 2147483647 2147483647]
 [         1          0 2147483647 2147483647 2147483647]
 [         6          4          4 2147483647 2147483647]
 [         9          6          6 2147483647 2147483647]
 [2147483647          9          9          7 2147483647]
 [2147483647         10         10         10 2147483647]
 [2147483647 2147483647         10         12         14]
 [2147483647 2147483647         14         12         12]
 [2147483647 2147483647 2147483647         12         14]]


In [5]:
[cost, D] = dtw_fast(s1, s2, window=1)
print(cost)
print(D)

17
[[         0 2147483647 2147483647 2147483647 2147483647]
 [         1 2147483647 2147483647 2147483647 2147483647]
 [2147483647          5 2147483647 2147483647 2147483647]
 [2147483647          7 2147483647 2147483647 2147483647]
 [2147483647 2147483647         10 2147483647 2147483647]
 [2147483647 2147483647         11 2147483647 2147483647]
 [2147483647 2147483647 2147483647         13 2147483647]
 [2147483647 2147483647 2147483647         15 2147483647]
 [2147483647 2147483647 2147483647 2147483647         17]]
